language: php

php:
  - 7.0

before_install:
  - phpenv config-add travis-php.ini

install:
  - composer --prefer-dist install

script:
  - ./phpcs --warning-severity=0 --standard=PSR2 src
  - ./phpunit tests
